apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-aws-secrets
  namespace: devpies
spec:
  provider: aws
  parameters:
    region: eu-central-1
    objects: |
      - objectName: production/myapp-secret-v3
        objectType: secretsmanager
        jmesPath:
            - path: username
              objectAlias: myusername
            - path: password
              objectAlias: mypassword
  secretObjects:
    - secretName: myapp-k8s-secret
      type: Opaque
      data:
        - objectName: myusername
          key: k8s-myusername
        - objectName: mypassword
          key: k8s-mypassword
